INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2025-12-30', 'regular', '[{"id": "meal-7", "name": "잡곡밥과 고등어구이", "phase": "regular", "mealTime": "breakfast", "nutrition": {"calories": 500, "protein": 25, "carbs": 70, "fat": 15}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-8", "name": "소고기 미역국과 밥", "phase": "regular", "mealTime": "lunch", "nutrition": {"calories": 600, "protein": 30, "carbs": 80, "fat": 20}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-9", "name": "닭가슴살 샐러드", "phase": "regular", "mealTime": "dinner", "nutrition": {"calories": 450, "protein": 35, "carbs": 40, "fat": 12}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2025-12-31', 'regular', '[{"id": "meal-7", "name": "잡곡밥과 고등어구이", "phase": "regular", "mealTime": "breakfast", "nutrition": {"calories": 500, "protein": 25, "carbs": 70, "fat": 15}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-8", "name": "소고기 미역국과 밥", "phase": "regular", "mealTime": "lunch", "nutrition": {"calories": 600, "protein": 30, "carbs": 80, "fat": 20}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-9", "name": "닭가슴살 샐러드", "phase": "regular", "mealTime": "dinner", "nutrition": {"calories": 450, "protein": 35, "carbs": 40, "fat": 12}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-01-01', 'liquid', '[{"id": "meal-1", "name": "미음", "phase": "liquid", "mealTime": "breakfast", "nutrition": {"calories": 150, "protein": 5, "carbs": 30, "fat": 2}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-2", "name": "채수", "phase": "liquid", "mealTime": "lunch", "nutrition": {"calories": 120, "protein": 2, "carbs": 25, "fat": 1}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-3", "name": "단호박 미음", "phase": "liquid", "mealTime": "dinner", "nutrition": {"calories": 180, "protein": 4, "carbs": 35, "fat": 2}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-01-02', 'liquid', '[{"id": "meal-1", "name": "미음", "phase": "liquid", "mealTime": "breakfast", "nutrition": {"calories": 150, "protein": 5, "carbs": 30, "fat": 2}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-2", "name": "채수", "phase": "liquid", "mealTime": "lunch", "nutrition": {"calories": 120, "protein": 2, "carbs": 25, "fat": 1}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-3", "name": "단호박 미음", "phase": "liquid", "mealTime": "dinner", "nutrition": {"calories": 180, "protein": 4, "carbs": 35, "fat": 2}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-01-03', 'liquid', '[{"id": "meal-1", "name": "미음", "phase": "liquid", "mealTime": "breakfast", "nutrition": {"calories": 150, "protein": 5, "carbs": 30, "fat": 2}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-2", "name": "채수", "phase": "liquid", "mealTime": "lunch", "nutrition": {"calories": 120, "protein": 2, "carbs": 25, "fat": 1}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-3", "name": "단호박 미음", "phase": "liquid", "mealTime": "dinner", "nutrition": {"calories": 180, "protein": 4, "carbs": 35, "fat": 2}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-01-04', 'liquid', '[{"id": "meal-1", "name": "미음", "phase": "liquid", "mealTime": "breakfast", "nutrition": {"calories": 150, "protein": 5, "carbs": 30, "fat": 2}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-2", "name": "채수", "phase": "liquid", "mealTime": "lunch", "nutrition": {"calories": 120, "protein": 2, "carbs": 25, "fat": 1}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-3", "name": "단호박 미음", "phase": "liquid", "mealTime": "dinner", "nutrition": {"calories": 180, "protein": 4, "carbs": 35, "fat": 2}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-01-05', 'liquid', '[{"id": "meal-1", "name": "미음", "phase": "liquid", "mealTime": "breakfast", "nutrition": {"calories": 150, "protein": 5, "carbs": 30, "fat": 2}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-2", "name": "채수", "phase": "liquid", "mealTime": "lunch", "nutrition": {"calories": 120, "protein": 2, "carbs": 25, "fat": 1}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-3", "name": "단호박 미음", "phase": "liquid", "mealTime": "dinner", "nutrition": {"calories": 180, "protein": 4, "carbs": 35, "fat": 2}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-01-06', 'liquid', '[{"id": "meal-1", "name": "미음", "phase": "liquid", "mealTime": "breakfast", "nutrition": {"calories": 150, "protein": 5, "carbs": 30, "fat": 2}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-2", "name": "채수", "phase": "liquid", "mealTime": "lunch", "nutrition": {"calories": 120, "protein": 2, "carbs": 25, "fat": 1}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-3", "name": "단호박 미음", "phase": "liquid", "mealTime": "dinner", "nutrition": {"calories": 180, "protein": 4, "carbs": 35, "fat": 2}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-01-07', 'liquid', '[{"id": "meal-1", "name": "미음", "phase": "liquid", "mealTime": "breakfast", "nutrition": {"calories": 150, "protein": 5, "carbs": 30, "fat": 2}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-2", "name": "채수", "phase": "liquid", "mealTime": "lunch", "nutrition": {"calories": 120, "protein": 2, "carbs": 25, "fat": 1}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-3", "name": "단호박 미음", "phase": "liquid", "mealTime": "dinner", "nutrition": {"calories": 180, "protein": 4, "carbs": 35, "fat": 2}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-01-08', 'liquid', '[{"id": "meal-1", "name": "미음", "phase": "liquid", "mealTime": "breakfast", "nutrition": {"calories": 150, "protein": 5, "carbs": 30, "fat": 2}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-2", "name": "채수", "phase": "liquid", "mealTime": "lunch", "nutrition": {"calories": 120, "protein": 2, "carbs": 25, "fat": 1}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-3", "name": "단호박 미음", "phase": "liquid", "mealTime": "dinner", "nutrition": {"calories": 180, "protein": 4, "carbs": 35, "fat": 2}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-01-09', 'soft', '[{"id": "meal-4", "name": "흰죽", "phase": "soft", "mealTime": "breakfast", "nutrition": {"calories": 250, "protein": 8, "carbs": 50, "fat": 3}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-5", "name": "계란찜과 무른 밥", "phase": "soft", "mealTime": "lunch", "nutrition": {"calories": 350, "protein": 15, "carbs": 60, "fat": 10}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-6", "name": "두부 조림과 야채죽", "phase": "soft", "mealTime": "dinner", "nutrition": {"calories": 300, "protein": 12, "carbs": 55, "fat": 6}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-01-10', 'soft', '[{"id": "meal-4", "name": "흰죽", "phase": "soft", "mealTime": "breakfast", "nutrition": {"calories": 250, "protein": 8, "carbs": 50, "fat": 3}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-5", "name": "계란찜과 무른 밥", "phase": "soft", "mealTime": "lunch", "nutrition": {"calories": 350, "protein": 15, "carbs": 60, "fat": 10}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-6", "name": "두부 조림과 야채죽", "phase": "soft", "mealTime": "dinner", "nutrition": {"calories": 300, "protein": 12, "carbs": 55, "fat": 6}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-01-11', 'soft', '[{"id": "meal-4", "name": "흰죽", "phase": "soft", "mealTime": "breakfast", "nutrition": {"calories": 250, "protein": 8, "carbs": 50, "fat": 3}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-5", "name": "계란찜과 무른 밥", "phase": "soft", "mealTime": "lunch", "nutrition": {"calories": 350, "protein": 15, "carbs": 60, "fat": 10}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-6", "name": "두부 조림과 야채죽", "phase": "soft", "mealTime": "dinner", "nutrition": {"calories": 300, "protein": 12, "carbs": 55, "fat": 6}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-01-12', 'soft', '[{"id": "meal-4", "name": "흰죽", "phase": "soft", "mealTime": "breakfast", "nutrition": {"calories": 250, "protein": 8, "carbs": 50, "fat": 3}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-5", "name": "계란찜과 무른 밥", "phase": "soft", "mealTime": "lunch", "nutrition": {"calories": 350, "protein": 15, "carbs": 60, "fat": 10}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-6", "name": "두부 조림과 야채죽", "phase": "soft", "mealTime": "dinner", "nutrition": {"calories": 300, "protein": 12, "carbs": 55, "fat": 6}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-01-13', 'soft', '[{"id": "meal-4", "name": "흰죽", "phase": "soft", "mealTime": "breakfast", "nutrition": {"calories": 250, "protein": 8, "carbs": 50, "fat": 3}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-5", "name": "계란찜과 무른 밥", "phase": "soft", "mealTime": "lunch", "nutrition": {"calories": 350, "protein": 15, "carbs": 60, "fat": 10}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-6", "name": "두부 조림과 야채죽", "phase": "soft", "mealTime": "dinner", "nutrition": {"calories": 300, "protein": 12, "carbs": 55, "fat": 6}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-01-14', 'soft', '[{"id": "meal-4", "name": "흰죽", "phase": "soft", "mealTime": "breakfast", "nutrition": {"calories": 250, "protein": 8, "carbs": 50, "fat": 3}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-5", "name": "계란찜과 무른 밥", "phase": "soft", "mealTime": "lunch", "nutrition": {"calories": 350, "protein": 15, "carbs": 60, "fat": 10}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-6", "name": "두부 조림과 야채죽", "phase": "soft", "mealTime": "dinner", "nutrition": {"calories": 300, "protein": 12, "carbs": 55, "fat": 6}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-01-15', 'soft', '[{"id": "meal-4", "name": "흰죽", "phase": "soft", "mealTime": "breakfast", "nutrition": {"calories": 250, "protein": 8, "carbs": 50, "fat": 3}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-5", "name": "계란찜과 무른 밥", "phase": "soft", "mealTime": "lunch", "nutrition": {"calories": 350, "protein": 15, "carbs": 60, "fat": 10}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-6", "name": "두부 조림과 야채죽", "phase": "soft", "mealTime": "dinner", "nutrition": {"calories": 300, "protein": 12, "carbs": 55, "fat": 6}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-01-16', 'soft', '[{"id": "meal-4", "name": "흰죽", "phase": "soft", "mealTime": "breakfast", "nutrition": {"calories": 250, "protein": 8, "carbs": 50, "fat": 3}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-5", "name": "계란찜과 무른 밥", "phase": "soft", "mealTime": "lunch", "nutrition": {"calories": 350, "protein": 15, "carbs": 60, "fat": 10}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-6", "name": "두부 조림과 야채죽", "phase": "soft", "mealTime": "dinner", "nutrition": {"calories": 300, "protein": 12, "carbs": 55, "fat": 6}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-01-17', 'soft', '[{"id": "meal-4", "name": "흰죽", "phase": "soft", "mealTime": "breakfast", "nutrition": {"calories": 250, "protein": 8, "carbs": 50, "fat": 3}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-5", "name": "계란찜과 무른 밥", "phase": "soft", "mealTime": "lunch", "nutrition": {"calories": 350, "protein": 15, "carbs": 60, "fat": 10}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-6", "name": "두부 조림과 야채죽", "phase": "soft", "mealTime": "dinner", "nutrition": {"calories": 300, "protein": 12, "carbs": 55, "fat": 6}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-01-18', 'soft', '[{"id": "meal-4", "name": "흰죽", "phase": "soft", "mealTime": "breakfast", "nutrition": {"calories": 250, "protein": 8, "carbs": 50, "fat": 3}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-5", "name": "계란찜과 무른 밥", "phase": "soft", "mealTime": "lunch", "nutrition": {"calories": 350, "protein": 15, "carbs": 60, "fat": 10}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-6", "name": "두부 조림과 야채죽", "phase": "soft", "mealTime": "dinner", "nutrition": {"calories": 300, "protein": 12, "carbs": 55, "fat": 6}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-01-19', 'soft', '[{"id": "meal-4", "name": "흰죽", "phase": "soft", "mealTime": "breakfast", "nutrition": {"calories": 250, "protein": 8, "carbs": 50, "fat": 3}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-5", "name": "계란찜과 무른 밥", "phase": "soft", "mealTime": "lunch", "nutrition": {"calories": 350, "protein": 15, "carbs": 60, "fat": 10}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-6", "name": "두부 조림과 야채죽", "phase": "soft", "mealTime": "dinner", "nutrition": {"calories": 300, "protein": 12, "carbs": 55, "fat": 6}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-01-20', 'soft', '[{"id": "meal-4", "name": "흰죽", "phase": "soft", "mealTime": "breakfast", "nutrition": {"calories": 250, "protein": 8, "carbs": 50, "fat": 3}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-5", "name": "계란찜과 무른 밥", "phase": "soft", "mealTime": "lunch", "nutrition": {"calories": 350, "protein": 15, "carbs": 60, "fat": 10}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-6", "name": "두부 조림과 야채죽", "phase": "soft", "mealTime": "dinner", "nutrition": {"calories": 300, "protein": 12, "carbs": 55, "fat": 6}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-01-21', 'soft', '[{"id": "meal-4", "name": "흰죽", "phase": "soft", "mealTime": "breakfast", "nutrition": {"calories": 250, "protein": 8, "carbs": 50, "fat": 3}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-5", "name": "계란찜과 무른 밥", "phase": "soft", "mealTime": "lunch", "nutrition": {"calories": 350, "protein": 15, "carbs": 60, "fat": 10}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-6", "name": "두부 조림과 야채죽", "phase": "soft", "mealTime": "dinner", "nutrition": {"calories": 300, "protein": 12, "carbs": 55, "fat": 6}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-01-22', 'soft', '[{"id": "meal-4", "name": "흰죽", "phase": "soft", "mealTime": "breakfast", "nutrition": {"calories": 250, "protein": 8, "carbs": 50, "fat": 3}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-5", "name": "계란찜과 무른 밥", "phase": "soft", "mealTime": "lunch", "nutrition": {"calories": 350, "protein": 15, "carbs": 60, "fat": 10}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-6", "name": "두부 조림과 야채죽", "phase": "soft", "mealTime": "dinner", "nutrition": {"calories": 300, "protein": 12, "carbs": 55, "fat": 6}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-01-23', 'soft', '[{"id": "meal-4", "name": "흰죽", "phase": "soft", "mealTime": "breakfast", "nutrition": {"calories": 250, "protein": 8, "carbs": 50, "fat": 3}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-5", "name": "계란찜과 무른 밥", "phase": "soft", "mealTime": "lunch", "nutrition": {"calories": 350, "protein": 15, "carbs": 60, "fat": 10}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-6", "name": "두부 조림과 야채죽", "phase": "soft", "mealTime": "dinner", "nutrition": {"calories": 300, "protein": 12, "carbs": 55, "fat": 6}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-01-24', 'soft', '[{"id": "meal-4", "name": "흰죽", "phase": "soft", "mealTime": "breakfast", "nutrition": {"calories": 250, "protein": 8, "carbs": 50, "fat": 3}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-5", "name": "계란찜과 무른 밥", "phase": "soft", "mealTime": "lunch", "nutrition": {"calories": 350, "protein": 15, "carbs": 60, "fat": 10}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-6", "name": "두부 조림과 야채죽", "phase": "soft", "mealTime": "dinner", "nutrition": {"calories": 300, "protein": 12, "carbs": 55, "fat": 6}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-01-25', 'soft', '[{"id": "meal-4", "name": "흰죽", "phase": "soft", "mealTime": "breakfast", "nutrition": {"calories": 250, "protein": 8, "carbs": 50, "fat": 3}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-5", "name": "계란찜과 무른 밥", "phase": "soft", "mealTime": "lunch", "nutrition": {"calories": 350, "protein": 15, "carbs": 60, "fat": 10}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-6", "name": "두부 조림과 야채죽", "phase": "soft", "mealTime": "dinner", "nutrition": {"calories": 300, "protein": 12, "carbs": 55, "fat": 6}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-01-26', 'soft', '[{"id": "meal-4", "name": "흰죽", "phase": "soft", "mealTime": "breakfast", "nutrition": {"calories": 250, "protein": 8, "carbs": 50, "fat": 3}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-5", "name": "계란찜과 무른 밥", "phase": "soft", "mealTime": "lunch", "nutrition": {"calories": 350, "protein": 15, "carbs": 60, "fat": 10}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-6", "name": "두부 조림과 야채죽", "phase": "soft", "mealTime": "dinner", "nutrition": {"calories": 300, "protein": 12, "carbs": 55, "fat": 6}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-01-27', 'soft', '[{"id": "meal-4", "name": "흰죽", "phase": "soft", "mealTime": "breakfast", "nutrition": {"calories": 250, "protein": 8, "carbs": 50, "fat": 3}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-5", "name": "계란찜과 무른 밥", "phase": "soft", "mealTime": "lunch", "nutrition": {"calories": 350, "protein": 15, "carbs": 60, "fat": 10}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-6", "name": "두부 조림과 야채죽", "phase": "soft", "mealTime": "dinner", "nutrition": {"calories": 300, "protein": 12, "carbs": 55, "fat": 6}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-01-28', 'soft', '[{"id": "meal-4", "name": "흰죽", "phase": "soft", "mealTime": "breakfast", "nutrition": {"calories": 250, "protein": 8, "carbs": 50, "fat": 3}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-5", "name": "계란찜과 무른 밥", "phase": "soft", "mealTime": "lunch", "nutrition": {"calories": 350, "protein": 15, "carbs": 60, "fat": 10}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-6", "name": "두부 조림과 야채죽", "phase": "soft", "mealTime": "dinner", "nutrition": {"calories": 300, "protein": 12, "carbs": 55, "fat": 6}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-01-29', 'soft', '[{"id": "meal-4", "name": "흰죽", "phase": "soft", "mealTime": "breakfast", "nutrition": {"calories": 250, "protein": 8, "carbs": 50, "fat": 3}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-5", "name": "계란찜과 무른 밥", "phase": "soft", "mealTime": "lunch", "nutrition": {"calories": 350, "protein": 15, "carbs": 60, "fat": 10}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-6", "name": "두부 조림과 야채죽", "phase": "soft", "mealTime": "dinner", "nutrition": {"calories": 300, "protein": 12, "carbs": 55, "fat": 6}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-01-30', 'soft', '[{"id": "meal-4", "name": "흰죽", "phase": "soft", "mealTime": "breakfast", "nutrition": {"calories": 250, "protein": 8, "carbs": 50, "fat": 3}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-5", "name": "계란찜과 무른 밥", "phase": "soft", "mealTime": "lunch", "nutrition": {"calories": 350, "protein": 15, "carbs": 60, "fat": 10}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-6", "name": "두부 조림과 야채죽", "phase": "soft", "mealTime": "dinner", "nutrition": {"calories": 300, "protein": 12, "carbs": 55, "fat": 6}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-01-31', 'soft', '[{"id": "meal-4", "name": "흰죽", "phase": "soft", "mealTime": "breakfast", "nutrition": {"calories": 250, "protein": 8, "carbs": 50, "fat": 3}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-5", "name": "계란찜과 무른 밥", "phase": "soft", "mealTime": "lunch", "nutrition": {"calories": 350, "protein": 15, "carbs": 60, "fat": 10}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-6", "name": "두부 조림과 야채죽", "phase": "soft", "mealTime": "dinner", "nutrition": {"calories": 300, "protein": 12, "carbs": 55, "fat": 6}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-02-01', 'regular', '[{"id": "meal-7", "name": "잡곡밥과 고등어구이", "phase": "regular", "mealTime": "breakfast", "nutrition": {"calories": 500, "protein": 25, "carbs": 70, "fat": 15}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-8", "name": "소고기 미역국과 밥", "phase": "regular", "mealTime": "lunch", "nutrition": {"calories": 600, "protein": 30, "carbs": 80, "fat": 20}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-9", "name": "닭가슴살 샐러드", "phase": "regular", "mealTime": "dinner", "nutrition": {"calories": 450, "protein": 35, "carbs": 40, "fat": 12}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-02-02', 'regular', '[{"id": "meal-7", "name": "잡곡밥과 고등어구이", "phase": "regular", "mealTime": "breakfast", "nutrition": {"calories": 500, "protein": 25, "carbs": 70, "fat": 15}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-8", "name": "소고기 미역국과 밥", "phase": "regular", "mealTime": "lunch", "nutrition": {"calories": 600, "protein": 30, "carbs": 80, "fat": 20}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-9", "name": "닭가슴살 샐러드", "phase": "regular", "mealTime": "dinner", "nutrition": {"calories": 450, "protein": 35, "carbs": 40, "fat": 12}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-02-03', 'regular', '[{"id": "meal-7", "name": "잡곡밥과 고등어구이", "phase": "regular", "mealTime": "breakfast", "nutrition": {"calories": 500, "protein": 25, "carbs": 70, "fat": 15}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-8", "name": "소고기 미역국과 밥", "phase": "regular", "mealTime": "lunch", "nutrition": {"calories": 600, "protein": 30, "carbs": 80, "fat": 20}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-9", "name": "닭가슴살 샐러드", "phase": "regular", "mealTime": "dinner", "nutrition": {"calories": 450, "protein": 35, "carbs": 40, "fat": 12}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-02-04', 'regular', '[{"id": "meal-7", "name": "잡곡밥과 고등어구이", "phase": "regular", "mealTime": "breakfast", "nutrition": {"calories": 500, "protein": 25, "carbs": 70, "fat": 15}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-8", "name": "소고기 미역국과 밥", "phase": "regular", "mealTime": "lunch", "nutrition": {"calories": 600, "protein": 30, "carbs": 80, "fat": 20}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-9", "name": "닭가슴살 샐러드", "phase": "regular", "mealTime": "dinner", "nutrition": {"calories": 450, "protein": 35, "carbs": 40, "fat": 12}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-02-05', 'regular', '[{"id": "meal-7", "name": "잡곡밥과 고등어구이", "phase": "regular", "mealTime": "breakfast", "nutrition": {"calories": 500, "protein": 25, "carbs": 70, "fat": 15}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-8", "name": "소고기 미역국과 밥", "phase": "regular", "mealTime": "lunch", "nutrition": {"calories": 600, "protein": 30, "carbs": 80, "fat": 20}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-9", "name": "닭가슴살 샐러드", "phase": "regular", "mealTime": "dinner", "nutrition": {"calories": 450, "protein": 35, "carbs": 40, "fat": 12}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-02-06', 'regular', '[{"id": "meal-7", "name": "잡곡밥과 고등어구이", "phase": "regular", "mealTime": "breakfast", "nutrition": {"calories": 500, "protein": 25, "carbs": 70, "fat": 15}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-8", "name": "소고기 미역국과 밥", "phase": "regular", "mealTime": "lunch", "nutrition": {"calories": 600, "protein": 30, "carbs": 80, "fat": 20}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-9", "name": "닭가슴살 샐러드", "phase": "regular", "mealTime": "dinner", "nutrition": {"calories": 450, "protein": 35, "carbs": 40, "fat": 12}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-02-07', 'regular', '[{"id": "meal-7", "name": "잡곡밥과 고등어구이", "phase": "regular", "mealTime": "breakfast", "nutrition": {"calories": 500, "protein": 25, "carbs": 70, "fat": 15}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-8", "name": "소고기 미역국과 밥", "phase": "regular", "mealTime": "lunch", "nutrition": {"calories": 600, "protein": 30, "carbs": 80, "fat": 20}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-9", "name": "닭가슴살 샐러드", "phase": "regular", "mealTime": "dinner", "nutrition": {"calories": 450, "protein": 35, "carbs": 40, "fat": 12}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-02-08', 'regular', '[{"id": "meal-7", "name": "잡곡밥과 고등어구이", "phase": "regular", "mealTime": "breakfast", "nutrition": {"calories": 500, "protein": 25, "carbs": 70, "fat": 15}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-8", "name": "소고기 미역국과 밥", "phase": "regular", "mealTime": "lunch", "nutrition": {"calories": 600, "protein": 30, "carbs": 80, "fat": 20}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-9", "name": "닭가슴살 샐러드", "phase": "regular", "mealTime": "dinner", "nutrition": {"calories": 450, "protein": 35, "carbs": 40, "fat": 12}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-02-09', 'regular', '[{"id": "meal-7", "name": "잡곡밥과 고등어구이", "phase": "regular", "mealTime": "breakfast", "nutrition": {"calories": 500, "protein": 25, "carbs": 70, "fat": 15}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-8", "name": "소고기 미역국과 밥", "phase": "regular", "mealTime": "lunch", "nutrition": {"calories": 600, "protein": 30, "carbs": 80, "fat": 20}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-9", "name": "닭가슴살 샐러드", "phase": "regular", "mealTime": "dinner", "nutrition": {"calories": 450, "protein": 35, "carbs": 40, "fat": 12}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-02-10', 'regular', '[{"id": "meal-7", "name": "잡곡밥과 고등어구이", "phase": "regular", "mealTime": "breakfast", "nutrition": {"calories": 500, "protein": 25, "carbs": 70, "fat": 15}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-8", "name": "소고기 미역국과 밥", "phase": "regular", "mealTime": "lunch", "nutrition": {"calories": 600, "protein": 30, "carbs": 80, "fat": 20}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-9", "name": "닭가슴살 샐러드", "phase": "regular", "mealTime": "dinner", "nutrition": {"calories": 450, "protein": 35, "carbs": 40, "fat": 12}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-02-11', 'regular', '[{"id": "meal-7", "name": "잡곡밥과 고등어구이", "phase": "regular", "mealTime": "breakfast", "nutrition": {"calories": 500, "protein": 25, "carbs": 70, "fat": 15}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-8", "name": "소고기 미역국과 밥", "phase": "regular", "mealTime": "lunch", "nutrition": {"calories": 600, "protein": 30, "carbs": 80, "fat": 20}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-9", "name": "닭가슴살 샐러드", "phase": "regular", "mealTime": "dinner", "nutrition": {"calories": 450, "protein": 35, "carbs": 40, "fat": 12}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-02-12', 'regular', '[{"id": "meal-7", "name": "잡곡밥과 고등어구이", "phase": "regular", "mealTime": "breakfast", "nutrition": {"calories": 500, "protein": 25, "carbs": 70, "fat": 15}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-8", "name": "소고기 미역국과 밥", "phase": "regular", "mealTime": "lunch", "nutrition": {"calories": 600, "protein": 30, "carbs": 80, "fat": 20}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-9", "name": "닭가슴살 샐러드", "phase": "regular", "mealTime": "dinner", "nutrition": {"calories": 450, "protein": 35, "carbs": 40, "fat": 12}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-02-13', 'regular', '[{"id": "meal-7", "name": "잡곡밥과 고등어구이", "phase": "regular", "mealTime": "breakfast", "nutrition": {"calories": 500, "protein": 25, "carbs": 70, "fat": 15}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-8", "name": "소고기 미역국과 밥", "phase": "regular", "mealTime": "lunch", "nutrition": {"calories": 600, "protein": 30, "carbs": 80, "fat": 20}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-9", "name": "닭가슴살 샐러드", "phase": "regular", "mealTime": "dinner", "nutrition": {"calories": 450, "protein": 35, "carbs": 40, "fat": 12}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-02-14', 'regular', '[{"id": "meal-7", "name": "잡곡밥과 고등어구이", "phase": "regular", "mealTime": "breakfast", "nutrition": {"calories": 500, "protein": 25, "carbs": 70, "fat": 15}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-8", "name": "소고기 미역국과 밥", "phase": "regular", "mealTime": "lunch", "nutrition": {"calories": 600, "protein": 30, "carbs": 80, "fat": 20}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-9", "name": "닭가슴살 샐러드", "phase": "regular", "mealTime": "dinner", "nutrition": {"calories": 450, "protein": 35, "carbs": 40, "fat": 12}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-02-15', 'regular', '[{"id": "meal-7", "name": "잡곡밥과 고등어구이", "phase": "regular", "mealTime": "breakfast", "nutrition": {"calories": 500, "protein": 25, "carbs": 70, "fat": 15}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-8", "name": "소고기 미역국과 밥", "phase": "regular", "mealTime": "lunch", "nutrition": {"calories": 600, "protein": 30, "carbs": 80, "fat": 20}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-9", "name": "닭가슴살 샐러드", "phase": "regular", "mealTime": "dinner", "nutrition": {"calories": 450, "protein": 35, "carbs": 40, "fat": 12}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-02-16', 'regular', '[{"id": "meal-7", "name": "잡곡밥과 고등어구이", "phase": "regular", "mealTime": "breakfast", "nutrition": {"calories": 500, "protein": 25, "carbs": 70, "fat": 15}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-8", "name": "소고기 미역국과 밥", "phase": "regular", "mealTime": "lunch", "nutrition": {"calories": 600, "protein": 30, "carbs": 80, "fat": 20}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-9", "name": "닭가슴살 샐러드", "phase": "regular", "mealTime": "dinner", "nutrition": {"calories": 450, "protein": 35, "carbs": 40, "fat": 12}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-02-17', 'regular', '[{"id": "meal-7", "name": "잡곡밥과 고등어구이", "phase": "regular", "mealTime": "breakfast", "nutrition": {"calories": 500, "protein": 25, "carbs": 70, "fat": 15}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-8", "name": "소고기 미역국과 밥", "phase": "regular", "mealTime": "lunch", "nutrition": {"calories": 600, "protein": 30, "carbs": 80, "fat": 20}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-9", "name": "닭가슴살 샐러드", "phase": "regular", "mealTime": "dinner", "nutrition": {"calories": 450, "protein": 35, "carbs": 40, "fat": 12}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-02-18', 'regular', '[{"id": "meal-7", "name": "잡곡밥과 고등어구이", "phase": "regular", "mealTime": "breakfast", "nutrition": {"calories": 500, "protein": 25, "carbs": 70, "fat": 15}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-8", "name": "소고기 미역국과 밥", "phase": "regular", "mealTime": "lunch", "nutrition": {"calories": 600, "protein": 30, "carbs": 80, "fat": 20}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-9", "name": "닭가슴살 샐러드", "phase": "regular", "mealTime": "dinner", "nutrition": {"calories": 450, "protein": 35, "carbs": 40, "fat": 12}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-02-19', 'regular', '[{"id": "meal-7", "name": "잡곡밥과 고등어구이", "phase": "regular", "mealTime": "breakfast", "nutrition": {"calories": 500, "protein": 25, "carbs": 70, "fat": 15}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-8", "name": "소고기 미역국과 밥", "phase": "regular", "mealTime": "lunch", "nutrition": {"calories": 600, "protein": 30, "carbs": 80, "fat": 20}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-9", "name": "닭가슴살 샐러드", "phase": "regular", "mealTime": "dinner", "nutrition": {"calories": 450, "protein": 35, "carbs": 40, "fat": 12}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-02-20', 'regular', '[{"id": "meal-7", "name": "잡곡밥과 고등어구이", "phase": "regular", "mealTime": "breakfast", "nutrition": {"calories": 500, "protein": 25, "carbs": 70, "fat": 15}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-8", "name": "소고기 미역국과 밥", "phase": "regular", "mealTime": "lunch", "nutrition": {"calories": 600, "protein": 30, "carbs": 80, "fat": 20}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-9", "name": "닭가슴살 샐러드", "phase": "regular", "mealTime": "dinner", "nutrition": {"calories": 450, "protein": 35, "carbs": 40, "fat": 12}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-02-21', 'regular', '[{"id": "meal-7", "name": "잡곡밥과 고등어구이", "phase": "regular", "mealTime": "breakfast", "nutrition": {"calories": 500, "protein": 25, "carbs": 70, "fat": 15}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-8", "name": "소고기 미역국과 밥", "phase": "regular", "mealTime": "lunch", "nutrition": {"calories": 600, "protein": 30, "carbs": 80, "fat": 20}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-9", "name": "닭가슴살 샐러드", "phase": "regular", "mealTime": "dinner", "nutrition": {"calories": 450, "protein": 35, "carbs": 40, "fat": 12}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-02-22', 'regular', '[{"id": "meal-7", "name": "잡곡밥과 고등어구이", "phase": "regular", "mealTime": "breakfast", "nutrition": {"calories": 500, "protein": 25, "carbs": 70, "fat": 15}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-8", "name": "소고기 미역국과 밥", "phase": "regular", "mealTime": "lunch", "nutrition": {"calories": 600, "protein": 30, "carbs": 80, "fat": 20}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-9", "name": "닭가슴살 샐러드", "phase": "regular", "mealTime": "dinner", "nutrition": {"calories": 450, "protein": 35, "carbs": 40, "fat": 12}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-02-23', 'regular', '[{"id": "meal-7", "name": "잡곡밥과 고등어구이", "phase": "regular", "mealTime": "breakfast", "nutrition": {"calories": 500, "protein": 25, "carbs": 70, "fat": 15}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-8", "name": "소고기 미역국과 밥", "phase": "regular", "mealTime": "lunch", "nutrition": {"calories": 600, "protein": 30, "carbs": 80, "fat": 20}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-9", "name": "닭가슴살 샐러드", "phase": "regular", "mealTime": "dinner", "nutrition": {"calories": 450, "protein": 35, "carbs": 40, "fat": 12}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-02-24', 'regular', '[{"id": "meal-7", "name": "잡곡밥과 고등어구이", "phase": "regular", "mealTime": "breakfast", "nutrition": {"calories": 500, "protein": 25, "carbs": 70, "fat": 15}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-8", "name": "소고기 미역국과 밥", "phase": "regular", "mealTime": "lunch", "nutrition": {"calories": 600, "protein": 30, "carbs": 80, "fat": 20}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-9", "name": "닭가슴살 샐러드", "phase": "regular", "mealTime": "dinner", "nutrition": {"calories": 450, "protein": 35, "carbs": 40, "fat": 12}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-02-25', 'regular', '[{"id": "meal-7", "name": "잡곡밥과 고등어구이", "phase": "regular", "mealTime": "breakfast", "nutrition": {"calories": 500, "protein": 25, "carbs": 70, "fat": 15}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-8", "name": "소고기 미역국과 밥", "phase": "regular", "mealTime": "lunch", "nutrition": {"calories": 600, "protein": 30, "carbs": 80, "fat": 20}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-9", "name": "닭가슴살 샐러드", "phase": "regular", "mealTime": "dinner", "nutrition": {"calories": 450, "protein": 35, "carbs": 40, "fat": 12}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-02-26', 'regular', '[{"id": "meal-7", "name": "잡곡밥과 고등어구이", "phase": "regular", "mealTime": "breakfast", "nutrition": {"calories": 500, "protein": 25, "carbs": 70, "fat": 15}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-8", "name": "소고기 미역국과 밥", "phase": "regular", "mealTime": "lunch", "nutrition": {"calories": 600, "protein": 30, "carbs": 80, "fat": 20}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-9", "name": "닭가슴살 샐러드", "phase": "regular", "mealTime": "dinner", "nutrition": {"calories": 450, "protein": 35, "carbs": 40, "fat": 12}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-02-27', 'regular', '[{"id": "meal-7", "name": "잡곡밥과 고등어구이", "phase": "regular", "mealTime": "breakfast", "nutrition": {"calories": 500, "protein": 25, "carbs": 70, "fat": 15}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-8", "name": "소고기 미역국과 밥", "phase": "regular", "mealTime": "lunch", "nutrition": {"calories": 600, "protein": 30, "carbs": 80, "fat": 20}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-9", "name": "닭가슴살 샐러드", "phase": "regular", "mealTime": "dinner", "nutrition": {"calories": 450, "protein": 35, "carbs": 40, "fat": 12}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-02-28', 'regular', '[{"id": "meal-7", "name": "잡곡밥과 고등어구이", "phase": "regular", "mealTime": "breakfast", "nutrition": {"calories": 500, "protein": 25, "carbs": 70, "fat": 15}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-8", "name": "소고기 미역국과 밥", "phase": "regular", "mealTime": "lunch", "nutrition": {"calories": 600, "protein": 30, "carbs": 80, "fat": 20}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-9", "name": "닭가슴살 샐러드", "phase": "regular", "mealTime": "dinner", "nutrition": {"calories": 450, "protein": 35, "carbs": 40, "fat": 12}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;

INSERT INTO meal_plans (user_id, date, recovery_phase, meals)
VALUES ('85d6d6b1-5af0-4b6d-ba2c-66125102a808', '2026-03-01', 'regular', '[{"id": "meal-7", "name": "잡곡밥과 고등어구이", "phase": "regular", "mealTime": "breakfast", "nutrition": {"calories": 500, "protein": 25, "carbs": 70, "fat": 15}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-8", "name": "소고기 미역국과 밥", "phase": "regular", "mealTime": "lunch", "nutrition": {"calories": 600, "protein": 30, "carbs": 80, "fat": 20}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}, {"id": "meal-9", "name": "닭가슴살 샐러드", "phase": "regular", "mealTime": "dinner", "nutrition": {"calories": 450, "protein": 35, "carbs": 40, "fat": 12}, "ingredients": ["식재료 1", "식재료 2"], "instructions": ["조리 단계 1", "조리 단계 2"], "prepTime": 15, "portionSize": "1인분"}]')
ON CONFLICT (user_id, date) DO UPDATE SET recovery_phase = EXCLUDED.recovery_phase, meals = EXCLUDED.meals;